### ISSUE TITLE
Missing  import BASE_DIR when using 'theme'  in config/settings/sample.local.py

### ISSUE THREAD

**Issue by jmfrenzel** [rdmorganiser/rdmo-app#1]
Using the ```config/settings/local.py```  being generated from ```config/settings/sample.local.py``` the app will not find start and crashes when having uncommented 
```python
THEME_DIR = os.path.join(BASE_DIR, 'theme')
```
The reason is that ```BASE_DIR``` is not defined because we also must import it in the first place via
```python
import os
from . import BASE_DIR
```

**Comment by jochenklar** [comment]
Thanks for the fix!
